#!/usr/bin/env python3
"""kappa-type near-miss test: does a covering exist with odd moduli dividing L, all distinct
EXCEPT that one modulus m may be used twice (extra copy)?  Uses exact_u.build plus one extra
modulus.  Prints the moduli m for which such a covering exists."""
import sys, time
from pysat.solvers import Cadical153
from exact_u import divisors

def decide_extra(L, extras, timeout=None):
    ds = divisors(L)
    mods = [(m, 0) for m in ds] + [(m, i + 1) for i, m in enumerate(extras)]
    var = {}; nv = 0
    for key in mods:
        m = key[0]
        for r in range(m):
            nv += 1; var[(key, r)] = nv
    cl = []
    for key in mods:
        m = key[0]
        xs = [var[(key, r)] for r in range(m)]
        s = []
        for i in range(m - 1):
            nv += 1; s.append(nv)
        for i in range(m):
            if i < m - 1: cl.append([-xs[i], s[i]])
            if i > 0:
                cl.append([-xs[i], -s[i - 1]])
                if i < m - 1: cl.append([-s[i - 1], s[i]])
    for t in range(L):
        cl.append([var[(key, t % key[0])] for key in mods])
    cl.append([var[((L, 0), 0)]])
    S = Cadical153(bootstrap_with=cl)
    t0 = time.time(); res = S.solve(); dt = time.time() - t0
    model = None
    if res:
        mm = set(l for l in S.get_model() if l > 0)
        model = sorted((key, r) for (key, r), v in var.items() if v in mm)
    S.delete()
    return res, dt, model

if __name__ == "__main__":
    L = int(sys.argv[1])
    found = []
    for m in divisors(L):
        res, dt, model = decide_extra(L, [m])
        print(f"L={L} extra copy of {m}: {res} ({dt:.1f}s)", flush=True)
        if res:
            found.append(m); print("  model:", model)
    print("kappa(L)<=1 witnesses:", found)
